library   : /home/grish/.beets/library.blb
directory : /home/grish/music
import:
    write              : yes
    copy               : no
    move               : yes
    incremental        : no
    timid              : no
    detail             : yes
    color              : yes
    threaded           : yes
    per_disc_numbering : yes
match:
    ignored  : missing_tracks unmatched_tracks
    preferred:
        countries     : ['US']
        media         : ['CD', 'Digital Media|File']
        original_year : yes
item_fields:
    track_title_snake: |
        track_pref = u'0' if track < 10 else u''
        smart_track = u'{tp}{tr}'.format(tp=track_pref, tr=track)
        return u'{d}_{tr}-{ti}'.format(d=disc, tr=smart_track, ti=title.lower().replace(' ', '_'))
paths:
    default   : $albumartist/[$original_year-$original_month] $album/$track_title_snake
    singleton : etc/no-album/$artist/$title_snake
    comp      : etc/compilations/[$original_year] $album/$track-$title_snake
plugins   : inline fetchart
fetchart:
    minwidth : 600
    sources: coverart itunes amazon albumart google wikipedia

