#!/usr/bin/zsh

# TODO: add in all of the general useful aliases we have

# wireless
# --------
wifi_connect() {
    wifi_file="/etc/wpa_supplicant/wireless_networks.conf"
    # use 'ip link' to find the wireless card interface, which will probably be
    # of the form wlpNsM, where N and M are integers
    net_card="wlp4s0"
    sudo pkill wpa_supplicant
    sudo dhcpcd -k
    sudo wpa_supplicant -B -Dnl80211 -i"$net_card" -c"$wifi_file"
    sudo dhcpcd "$net_card"
}

