#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/src/bitswap-tests"
    WENV_DEPS=('iptb')
    WENV_PROJECT='bitswap-tests'
    WENV_BRANCH='master'
    wenv_init() {
        sudo systemctl start docker
    }
    wenv_shutdown() {
        clean
        iptb stop
        sudo systemctl stop docker
    }
}

# init() {
#     num="$1"
#     [[ -z "$num" ]] && num=3
#     yes | iptb init -n $num --type docker
# }

# reinit() {
#     iptb kill
#     init "$1"
# }

c() {
    dest="$1"
    case "$dest" in
        ipfs)
            cd "$GOPATH/src/github.com/ipfs/go-ipfs"
            ;;
        iptb)
            cd "$GOPATH/src/github.com/ipfs/iptb"
            ;;
        cnet)
            cd "$GOPATH/src/github.com/whyrusleeping/go-ctrlnet"
            ;;
        ipfs)
            cd "$GOPATH/src/github.com/ipfs/go-ipfs"
            ;;
        bs|bitswap)
            cd "$GOPATH/src/github.com/ipfs/go-bitswap"
            ;;
        *)
            return 1
            ;;
    esac
}
