#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/src/bitswap-tests"
    WENV_ALIASES=()
    WENV_PROJECT='bitswap-tests'
    WENV_BRANCH='master'
    wenv_init() {
        sudo systemctl start docker
    }
    wenv_shutdown() {
        iptb kill
        sudo systemctl stop docker
    }
}

export IPTB_ROOT="$HOME/.iptb"

init() {
    num="$1"
    [[ -z "$num" ]] && num=3
    yes | iptb init -n $num --type docker
}

reinit() {
    iptb kill
    init "$1"
}

c() {
    dest="$1"
    case "$dest" in
        iptb)
            cd "$GOPATH/src/github.com/whyrusleeping/iptb"
            ;;
        cnet)
            cd "$GOPATH/src/github.com/whyrusleeping/go-ctrlnet"
            ;;
        *)
            return 1
            ;;
    esac
}


