#!/usr/bin/env zsh

wenv_setup() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/kubernetes-ipfs/ipfs-cluster"
    WENV_DEPS=('ipfs' 'iptl')
    WENV_PROJECT='run-parameterized-tests'

    wenv_init() { }
}

