#!/usr/bin/zsh

wenv_setup() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/ipfs-cluster"
    WENV_DEPS=('ipfs' 'iptl')
    WENV_PROJECT='ipfs-cluster'
    unset WENV_BRANCH
    WENV_TASK=73

    wenv_init() { }
    wenv_shutdown() { }
}

sharness_setup() {
    while getopts ":r" opt; do
        case $opt in
            r) sharness_reset ;;
            *) echo "Invalid flag"; return 1 ;;
        esac
    done

    systemctl --user stop ipfs 2>/dev/null
    sudo systemctl restart docker
    docker rm ipfs 2>/dev/null
    lib_dir="$GOPATH/src/github.com/ipfs/ipfs-cluster/sharness/lib"
    if [[ ! -d "$lib_dir/sharness" ]]; then
        ln -s "$GOPATH/src/github.com/chriscool/sharness" "$lib_dir"
    fi
    wenv cd
    cd sharness
}

sharness_run() {
    [[ ! -f "$1" ]] && return 1
    # kill ipfs-cluster-service (shortened name for some reason)
    pkill ipfs-cluster-se
    $@
}
alias run='sharness_run'

sharness_reset() {
    wenv cd
    make clean
    make install
    pkill ipfs-cluster-se
}
