#!/bin/zsh

wenv_setup() {
    typeset -Ag WENV_CONSTS
    WENV_CONSTS[DIR]="$GOPATH/src/github.com/ipfs/go-ipfs-config"
    WENV_DEPS=()
    WENV_CONSTS[NAME]='go-ipfs-config'
    WENV_CONSTS[BRANCH]='experimental/bitswap-strategy-config'
    wenv_init() {
        wenv_tmux_layout 'tasks'
        # edit_project
    }
    wenv_shutdown() { }
}

edit_project() {
        workfile="$1"
        [[ -z "$workfile" ]] && return 1
        session=${${workfile#*/}%%.*}
        wenv_tmux_split v "kak -s $session $workfile $GOPATH/src/github.com/ipfs/go-ipfs/repo/config/$workfile"
        tmux select-pane -U
        until kak -l | grep "$session"; do :; done
        kak -c "$session" -e 'buffer-next'
}
