#!/bin/zsh

wenv_setup() {
    WENV_DIR="$SRC/strategy_sim"
    WENV_ALIASES=('python')
    WENV_PROJECT='strategy_sim'
    WENV_BRANCH='feat/incremental-exchanges'
    unset WENV_TASK
    wenv_init() {
        wenv_tmux_layout tasks
        tmux rename-window 'src'
        wenv_tmux_split -n 'run' c
        tmux select-window -t1
        $EDITOR src/strategy_sim/sim.py
    }
    wenv_shutdown() {
        # TODO: how to do this?
        #[[ $PIPENV_ACTIVE -eq 1 ]] && echo 'hi' && exit
    }
}
