#!/bin/zsh

# X aliases
# =========

# backlight
# -------
xb() { xbacklight $1% }

# change pdf viewer
# -----------------
alias pdf='zathura'

# steam
# -----
alias stm='LD_PRELOAD='"'"'/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so'"'"' steam'

# ncmpcpp/visualizer (for album art)
if [[ ! -n "$TMUX" ]]; then
    alias ncmpcpp='urxvt --shading 0 -e zsh -c "/bin/ncmpcpp ; zsh -i" &; exit'
    # alias cava='urxvt --shading 0 -e zsh -c "/bin/cava ; zsh -i" &; exit'
    alias cava='urxvt --shading 0 -e zsh -c "mpd_watch.sh \"mnuc2; dynamic_cava_colors >/home/grish/scratch/dynamic_cava_colors-log 2>&1\" &; /bin/cava; zsh -i" &; exit'
fi

set_window_name() {
    eval 'precmd() {echo -ne "\033]0;'"$*"'\007"}'
}
set_default_window_name() {
    set_window_name "\$(echo $USER@$(hostname): \$(pwd) | sed 's|'"$HOME"'|~|')"
}
[[ -z "$WENV" ]] && set_default_window_name

# hdmi
# ----
hdmi-on() {
    arg="$1"
    shift
    case "$arg" in
        'home'|'insignia'|'tv')
            opts="--right-of DP-0 --scale 1.2x1.2 $@"
            ;;
        'class')
            opts="--mode 1920x1080 --same-as DP-0 $@"
            ;;
        'work')
            $HOME/.screenlayout/work.sh
            feh --bg-center --randomize --no-fehbg '/home/grish/media/pictures/backgrounds/cowboy_bebop/spike_ship_outline-no_title.jpg' /home/grish/media/pictures/backgrounds/*-bw.{jpg,png}
            return 0
            ;;
        *)
            opts="--auto --above DP-0 $@"
            ;;
    esac
    xrandr --output HDMI-0 `echo "$opts"` && $HOME/.fehbg
}
alias hdmi-off="xrandr --output HDMI-0 --off && $HOME/.fehbg"
