#!/bin/zsh

file="$1"
shift
preamble="preamble.tex"

if [[ ! -f "$file.md" ]]; then
    echo "usage: $0 <file name (w/o extension)>"
    exit 1
fi

pandoc_flags=("-s" "-f markdown" "-t latex" "-o $file.tex")

for input in "$@"; do
    pandoc_flags+="$input"
done

if [[ -f "$file.pre" ]]; then
    pandoc_flags+="-H $file.pre"
elif [[ -f "$preamble" ]]; then
    pandoc_flags+="-H $preamble"
elif [[ -f "../$preamble" ]]; then
    pandoc_flags+="-H ../$preamble"
fi

pandoc_cmd="pandoc"

for flag in $pandoc_flags; do
    pandoc_cmd+=" $flag"
done

pandoc_cmd+=" $file.md"

printf "$pandoc_cmd"

zsh -c "$pandoc_cmd"
