
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -f "$HOME/dotfiles/zsh/aliases" ]] && source "$HOME/dotfiles/zsh/aliases"
[[ -f "$HOME/dotfiles/etc/zsh/aliases" ]] && source "$HOME/dotfiles/etc/zsh/aliases"

LS_COLORS="$LS_Colors:di=01;36"
