#!/bin/zsh

wenv_setup() {
    WENV_DIR=""
    WENV_ALIASES=('x')
    WENV_PROJECT=''
    WENV_BRANCH=''
    wenv_init() {
    }
    wenv_shutdown() {
        aws stop
    }
}

INSTANCE_ID='i-02ee6c7435f38ea79'

aws_start() {
    /bin/aws ec2 start-instances --instance-ids $INSTANCE_ID
}

aws_stop() {
    /bin/aws ec2 stop-instances --instance-ids $INSTANCE_ID
}

aws_status() {
    /bin/aws ec2 describe-instance-status --instance-ids $INSTANCE_ID
}

aws_ssh() {
    while getopts ':w:' opt; do
        case $opt in
            w) [[ ! -z "$OPTARG" ]] && WINDOW_NAME='$USER@$(hostname) '"#$OPTARG" ;;
        esac
    done
    shift $((OPTIND-1))

    dst='aws'
    [ "$1" = 'root' ] && dst='aws-root' && shift
    addr=$(/bin/aws ec2 describe-instances --instance-ids $INSTANCE_ID |
           jq --raw-output '.Reservations[0] | .Instances[0] | .PublicIpAddress')

    ssh -t $dst -o Hostname=$addr "$@" 'echo -ne "\033]0;$WINDOW_NAME\a"; zsh'
}

aws_scp() {
    addr=$(/bin/aws ec2 describe-instances --instance-ids $INSTANCE_ID |
           jq --raw-output '.Reservations[0] | .Instances[0] | .PublicIpAddress')
    scp -o Hostname="$addr" $@
}

aws_rsync() {
    addr=$(/bin/aws ec2 describe-instances --instance-ids $INSTANCE_ID |
           jq --raw-output '.Reservations[0] | .Instances[0] | .PublicIpAddress')
    rsync -rtzpP -e "ssh -o Hostname=$addr" --delete $@
}

aws() {
    arg="$1"
    shift
    case "$arg" in
        start)
            aws_start $@
            ;;
        stop)
            aws_stop $@
            ;;
        status)
            aws_status $@
            ;;
        ssh)
            aws_ssh $@
            ;;
        scp)
            aws_scp $@
            ;;
        rsync)
            aws_rsync $@
            ;;
        *)
            /bin/aws "$1" "$@"
            ;;
    esac
}
