#!/usr/bin/env zsh

wenv_setup() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/ipfs-cluster"
    WENV_ALIASES=('ipfs' 'iptl')
    WENV_PROJECT='ipfs-cluster-pnets'
    WENV_BRANCH='feat/pnet'

    wenv_init() {
        if [[ -n "$TMUX" ]]; then
            #wenv_tmux_split h
            #tmux send-keys 'kak ipfs-cluster-service/main.go' 'Enter' '239g' 'Enter'
        fi
    }
}
