#!/bin/zsh

wenv_setup() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/go-ipfs"
    WENV_ALIASES=()
    WENV_PROJECT=''
    WENV_BRANCH='impl/bitswap/round-robin-prq'
    wenv_init() { }
}

ipfs() {
    case "$1" in
        'public')      config='--config ~/.ipfs'
                       shift
                       ;;
        'p'|'private') config='--config ~/.ipfs-private'
                       shift
                       ;;
        *)             config=''
                       ;;
    esac

    eval $GOPATH/bin/ipfs "$config" $@
}
