#!/bin/zsh

wenv_setup() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision"
    WENV_ALIASES=()
    WENV_PROJECT='round-robin-prq'
    WENV_BRANCH='impl/bitswap/round-robin-prq'
    wenv_init() { }
    wenv_shutdown() { }
}
