#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/work/research/meetings/presentations/cur"
    WENV_ALIASES=('md')
    WENV_PROJECT=''
    WENV_BRANCH='master'
    wenv_init() {
        mendeleydesktop paper.pdf &
        slides_dev 'presentation.md'
    }
    wenv_shutdown() { }
}
