#!/bin/zsh

wenv_setup() {
    WENV_DIR="$SCRATCH/rust"
    #WENV_DIR="$WENV_DIR/variables"
    unset WENV_ALIASES
    WENV_PROJECT="$WENV"

    wenv_init() {
        wenv_tmux_split h
        tmux send-keys 'w3m "file:///home/grish/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/book/index.html"' 'Enter'
    }
}
