#!/bin/zsh

# X aliases
# =========

# backlight
# -------
xb() { xbacklight $1% }

# change pdf viewer
# -----------------
alias pdf='zathura'

# steam
# -----
alias stm='LD_PRELOAD='"'"'/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so'"'"' steam'

# ncmpcpp (for album art)
if [[ ! -n "$TMUX" ]]; then
    alias ncmpcpp='urxvt --shading 0 -e zsh -c "/bin/ncmpcpp ; zsh -i" &; exit'
fi

set_window_name() {
    eval 'precmd (){xdotool set_window --name "'"$*"'" $(xdotool getactivewindow)}'
}
[[ $(whence -w precmd) = *none ]] && set_window_name "$(echo $USER@$(hostname): $(pwd) | sed 's|'"$HOME"'|~|')"

# hdmi
# ----
hdmi-on() {
    arg="$1"
    shift
    case "$arg" in
        'home'|'insignia'|'tv')
            opts="--right-of DP-0 --scale 1.2x1.2 $@"
            ;;
        'class')
            opts="--mode 1920x1080 --same-as DP-0 $@"
            ;;
        *)
            opts="--auto --above DP-0 $@"
            ;;
    esac
    xrandr --output HDMI-0 `echo "$opts"` && $HOME/.fehbg
}
alias hdmi-off="xrandr --output HDMI-0 --off && $HOME/.fehbg"
