#!/bin/zsh

# X aliases
# =========

# backlight
# -------
xb() { xbacklight $1% }

# change pdf viewer
# -----------------
alias pdf='zathura'

# steam
# -----
alias stm='LD_PRELOAD='"'"'/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so'"'"' steam'

# ncmpcpp (for album art)
alias ncmpcpp='urxvt --shading 0 -e zsh -c "/bin/ncmpcpp ; zsh -i" &; exit'

# hdmi
# ----
hdmi-on() {
    arg="$1"
    if [[ ! -z "$arg" ]]; then
        arg=""
        shift
    fi
    case "$arg" in
        'home'|'insignia'|'tv')
            opts="--right-of DP-0 --scale 1.2x1.2 $@"
            ;;
        *)
            opts="--auto --above DP-0 $@"
            ;;
    esac
    xrandr --output HDMI-0 `echo "$opts"` && $HOME/.fehbg
}
alias hdmi-off="xrandr --output HDMI-0 --off && $HOME/.fehbg"

